const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  OPERATIONS: "OPERATIONS",
  USER: "USER",
};

const ROLE_GROUPS = {
  ADMIN_ONLY: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  STAFF: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.OPERATIONS],
  ALL_AUTHENTICATED: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.OPERATIONS, ROLES.USER],
};

module.exports = { ROLES, ROLE_GROUPS };
